language: go
sudo: false
go:
         - 1.6
         - 1.7
         - 1.8

install: go get -v ./hipchat
script:
    - go get -u golang.org/x/lint/golint
    - golint ./...
    - test `gofmt -l . | wc -l` = 0
    - make

matrix:
    allow_failures:
         go: tip
